Tracardi/tracardi-api

- app/api/event_tag_endpoint.py
added /event/tag/delete/{event_type} endpoint to delete docs in tag index basing on event type, added delete function to tag driver to delete doc by index (type)
> issue #150

- app/api/consent_type_endpoint.py
Please DO NOT DELETE this template. Fill it. PR without this template will be discarded. We need your declaration that
your contribution is MIT licensed without it, we can not merge your code.
PRs without ticked MIT license will bot be accepted - Sorry. 
---
usecase #196 + prepared for #211 (consent plug-in)
----
**Please** following this checklist to help us incorporate your contribution quickly and easily:
> usecase #196 + prepared for #211 (consent plug-in)

- app/setup/mappings/resource-index.json
Modifies resource mapping. 
----
> modified resource-index.json (#236)

- app/api/auth/authentication.py
- app/api/user_endpoint.py
- app/main.py
- app/setup/mappings/user-index.json
user index, add/ update users, remove users (#241, #242, #243)
New user management system, endpoints: adding and removing users, services: login service + plugged service into 
authorization
----
> user index, add/ update users, remove users (#241, #242, #243)

- app/setup/mappings/segment-index.json
Modified segment index and model, so we can return machine name (#263)
Modified segment index and model, so we can return machine name (#263)
> Modified segment index and model, so we can return machine name (#263)

- app/setup/on_start.py
added consent-plugin to tracardi and tracardi-API (#211)
added consent-plugin to tracardi and tracardi-API (#211)
----
> added consent-plugin to tracardi and tracardi-API (#211)

- app/setup/on_start.py
- manual/en/docs/flow/actions/add_consents_action.md
- manual/en/docs/flow/actions/calculate_time_difference_action.md
added time difference plugin and documentation for consent plugin (#283, #280)
added time difference plugin (with all things like models, configs, validators and so on) + missing documentation to consent 
plugin.
----
> added time difference plugin and documentation for consent plugin (#283, #280)

- test/tracardi/test_event_validator.py
Validation fix (#334)
----fixed event validation bug, wrote new test for validation service
> validation fix (#334)

- app/setup/on_start.py
- manual/en/docs/flow/actions/switch_action.md
switch plugin (#335)
added switch plugin
> switch plugin (#335)

- app/setup/on_start.py
- manual/en/docs/flow/actions/regex/regex_replace_action.md
regex replace plugin (#348)
Added regex replace plugin
----
> regex replace plugin (#348)

- app/setup/on_start.py
- manual/en/docs/flow/actions/validate_with_json_schema_action.md
JSON schema validation plugin (#346)
----added JSON schema validation plugin
> JSON schema validation plugin (#346)

- app/api/resource_endpoint.py
- app/setup/on_start.py
- manual/en/docs/flow/actions/fetch_mixpanel_funnel_action.md
- manual/en/docs/flow/actions/send_to_mixpanel_action.md
mixpanel plugins (#330)
Added mixpanel plugins' documentation
----
> mixpanel plugins (#330)

- app/api/user_endpoint.py
- app/setup/mappings/user-index.json
User endpoints (#74, #240)
added functionalities required for user management site to work.
----
> User endpoints (#74, #240)

- test/tracardi/test_dot_accessor.py
dot_accessor casting + tests (#375)
----added casting functionality to dot_accessor
> dot_accessor casting + tests (#375)

- app/api/consent_type_endpoint.py
- app/api/credentials_endpoint.py
- app/api/debug_endpoint.py
- app/api/destination_endpoint.py
- app/api/event_endpoint.py
- app/api/event_schema_validation_endpoint.py
- app/api/event_source_endpoint.py
- app/api/event_tag_endpoint.py
- app/api/flow_endpoint.py
- app/api/flows_endpoint.py
- app/api/health_endpoint.py
- app/api/info_endpoint.py
- app/api/instance_endpoint.py
- app/api/log_endpoint.py
- app/api/plugins_endpoint.py
- app/api/profile_endpoint.py
- app/api/project_endpoint.py
- app/api/purchases_endpoint.py
- app/api/rule_endpoint.py
- app/api/segments_endpoint.py
- app/api/session_endpoint.py
- app/api/settings_endpoint.py
- app/api/storage_endpoint.py
- app/api/test_endpoint.py
- app/api/token_endpoint.py
- app/api/tql_endpoint.py
- app/api/tracardi_pro_endpoint.py
- app/api/user_endpoint.py
added documentation for API (#57)
----like in title
> added documentation for API (#57)

- test/plugins/unit/test_plugin_profile_segmentation.py
- test/plugins/unit/test_plugin_regex_match.py
- test/plugins/unit/test_plugin_regex_replace.py
- test/plugins/unit/test_plugin_string_operations.py
- test/plugins/unit/test_plugin_to_json.py
plugin tests + bug fixes 
like in title
----
> plugin tests + bug fixes 

- app/api/resource_endpoint.py
- app/setup/on_start.py
- manual/en/docs/flow/actions/fetch_from_airtable_action.md
- manual/en/docs/flow/actions/send_to_airtable_action.md
Airtable plugins (#89)
added Airtable plugins
----
> Airtable plugins (#89)

- app/api/event_schema_validation_endpoint.py
- test/api/test_consent_type.py
- test/api/test_event_tag.py
- test/api/test_user.py
- test/api/test_validation_schema.py
- test/utils.py
endpoints tests
like in title
----
> endpoints tests

- app/setup/on_start.py
- manual/en/docs/flow/actions/assign_condition_result_action.md
assign condition result plugin (#377)
added assign condition result plugin
----
> assign condition result plugin (#377)

- app/setup/on_start.py
- manual/en/docs/flow/actions/condition_set_action.md
- test/plugins/unit/test_plugin_condition_set.py
Conditions set plugin (#376)
---- plugin, tests, manual
PRs without ticked MIT license will bot be accepted - Sorry.
> Conditions set plugin (#376)

- app/api/event_tag_endpoint.py
event tagging site requirements (#371)
added event taggin site
----
> event tagger site requirements (#371)

- app/setup/on_start.py
- manual/en/docs/flow/actions/reduce_array_action.md
reduce array plugin (#390)
----Added array-reducing plugin
> reduce array plugin (#390)

- manual/en/docs/flow/actions/contact_popup_action.md
- manual/en/docs/flow/actions/rating_popup_action.md
docs for contact popup widget plugin (#397)
added documentation to contact popup plugin
----
> docs for contact popup widget plugin (#397)

- app/api/auth/authentication.py
- app/api/token_endpoint.py
- app/api/user_log_endpoint.py
- app/main.py
- app/setup/mappings/user-log-index.json
user log-in logging (#398)
----added user log-in logging system
> user log-in logging (#398)

- app/api/event_tag_endpoint.py
- app/api/user_endpoint.py
- test/api/test_event_tag.py
Endpoint renaming (#406)
renamed endpoints
----
> Endpoint renaming (#406)

- app/api/user_endpoint.py
user self-edit site
added the page where user can change their account's properties
----
> user self-edit site

- app/api/user_account_endpoint.py
- app/api/user_endpoint.py
- app/main.py
Bug fixes (#69)
removed bugs related to user page
----
> Bug fixes (#69)

- app/api/flow_action_endpoint.py
new plugin details form endpoints (#102)
added new endpoints to handle edits in new plugin form
----
> new plugin details form endpoints (#102)

- app/api/flow_action_endpoint.py
improved WF search engine (#412, #413)
like in title
----
> improved WF search engine (#412, #413)

- app/api/test_endpoint.py
Redis and ES health check endpoints (#415)
added new endpoints
----
> Redis and ES health check endpoints (#415)

- manual/en/docs/flow/actions/get_prev_session_action.md
last session plugin (#417)
added plugin that finds nth last session for the current profile
----
> last session plugin (#417)

- manual/en/docs/flow/actions/get_prev_event_action.md
get previous event plugin (#416)
----
> get previous event plugin (#416)

- app/api/log_endpoint.py
filtering logs (#422)
----used new driver functionality in logs endpoint
> filtering logs

- app/config.py
- app/main.py
- app/setup/on_start.py
dead instance removal (#426)
added removing dead instances functionality
----
> dead instance removal (#426)

- app/api/event_endpoint.py
event source traffic details (#424)
----added API endpoints required for this task
> event source traffic details (#424)

- manual/en/docs/notations/logic_notation.md
- test/tracardi/test_tql.py
parser fixes, added empty operator (#251, #407)
----fixed parser bugs, added new EMPTY/ NOT EMPTY functionality
> parser fixes, added empty operator (#251, #407)

- manual/en/docs/flow/actions/read_from_memory_action.md
- manual/en/docs/flow/actions/write_to_memory_action.md
memory plugins (#81)
----added memory plugins 
> memory plugins (#81)

- app/api/consent_type_endpoint.py
- manual/en/docs/flow/actions/require_consents_action.md
Require consents plugin (#414)
----added plugin that checks for consents in profile data
> require consent plugin documentation (#414)

- app/api/consent_type_endpoint.py
- manual/en/docs/flow/actions/add_consents_action.md
Consent plugins fix
fixed consent system so that it's consistent
----
> Consent plugins fix

- app/setup/on_start.py
api instance removing bug fix
added refresh after deletion
----
> api instance removing bug fix

- app/api/flow_endpoint.py
wf name bug fix (#258)
fixed bug mentioned in the issue
----
> wf name bug fix (#258)

- manual/en/docs/flow/actions/send_to_slack_channel_action.md
> minor slack plugin fixes

- manual/en/docs/flow/actions/add_active_campaign_contact_action.md
- manual/en/docs/flow/actions/fetch_ac_contact_by_email_action.md
active campaign plugins v1
added active campaign integration
----
> active campaign plugins v1

- app/api/plugins_endpoint.py
plugin Endpoint class implementation
implemented Endpoint class 
----
> plugin Endpoint class implementation

- app/api/batch_endpoint.py
- app/api/plugins_endpoint.py
- app/api/scheduler/scheduler_endpoint.py
- app/api/task_endpoint.py
- app/main.py
> Batch imports

- manual/en/docs/flow/actions/send_to_data_extension_action.md
Marketing cloud data extension plugin
----
> Marketing cloud data extension plugin

- manual/en/docs/flow/actions/assign_profile_id_action.md
- manual/en/docs/flow/actions/log_message_action.md
- manual/en/docs/flow/actions/throw_error_action.md
docs for throw error, assign profile id and log message (#460)
----
> docs for throw error, assign profile id and log message (#460)

- app/api/test_endpoint.py
- app/main.py
cluster health info (#464)
----
> cluster health info (#464)

- app/api/test_endpoint.py
> indices endpoint (#97)

- app/api/auth/authentication.py
- app/api/auth/permissions.py
- app/api/auth/user_db.py
- app/api/settings_endpoint.py
- app/api/token_endpoint.py
- test/api/test_redis_auth.py
- test/utils.py
caching tokens on Redis (#483)
----
> caching tokens on Redis (#483)

- app/api/storage_endpoint.py
deleting indices API (#491)
added endpoint for deleting indices
----
> deleting indices API (#491)

- manual/en/docs/flow/actions/start_action.md
- manual/en/mkdocs.yml
- test/api/test_flow.py
- test/end_2_end/test_end_to_end.py
- test/end_2_end/test_multiple_events_in_tracker.py
- test/end_2_end/test_multiple_events_in_tracker_different_events.py
- test/end_2_end/test_overriding_profile_traits.py
- test/end_2_end/test_quick_profile_concurrent_update.py
- test/end_2_end/test_quick_profile_update.py
- test/plugins/unit/test_plugin_start.py
start and debug node merge (#475)
----
> start and debug node merge (#475)

- app/api/flow_endpoint.py
flow enabling bug fix (#524)
----
> flow enabling bug fix (#524)

- manual/en/docs/flow/actions/remote_call_action.md
remote call API plugin redo (#509)
redone remote call plugin to use resource
----
> remote call API plugin redo (#509)

- app/api/flow_endpoint.py
- test/end_2_end/test_end_to_end.py
nodes rearrangement (#488)
----
> nodes rearrangement (#488)

- app/api/flow_endpoint.py
flow enabling regression (#527)
----
> flow enabling regression (#527)

- manual/en/docs/flow/actions/field_type_action.md
added field info plugin (#539)
----
> added field info plugin

- app/api/migration_endpoint.py
minor migration bug fixes, minor improvements (#181)
----
> minor migration bug fixes, minor improvements (#181)

- manual/en/docs/flow/actions/append_remove_trait_action.md
- manual/en/docs/flow/actions/remote_call_action.md
added missing plugin docs (#538, #521)
> added missing plugin docs (#538, #521)

- app/api/install_endpoint.py
instance not visible after install bug fix (#563)
> instance not visible after install bug fix (#563)

- app/api/auth/token_memory.py
added elastic identifier to redis auth tokens Fixes tracardi#577
> added elastic identifier to redis auth tokens (#577)

- app/api/auth/authentication.py
- app/api/auth/token_memory.py
- app/api/auth/user_db.py
- app/api/domain/user_payload.py
- app/api/user_endpoint.py
- app/service/user_manager.py
user account expiration date (#523)
----
**Please** following this checklist to help us incorporate your contribution quickly and easily:
> user account expiration date (#523)

- app/api/event_management_endpoint.py
- app/api/event_tag_endpoint.py
- test/api/test_event_tagging.py
- test/api/test_flow.py
> api tests now pass (#120)

- manual/en/docs/flow/actions/generic_uix_action.md
> generic UIX plugin

- manual/en/docs/flow/password_generator_action.md
- test/plugins/unit/test_plugin_random_password_generator.py
be discarded. 
Tips
* Test your code throughly before PR.
Password Generator Action
Test and documentation for password generator plugin
----
To make clear that you license your contribution under the MIT you have to …
> 607 password generator

- manual/en/docs/resources/redis_resource.md
resource type refactoring + documenting resources (#510)
> resource type refactoring + documenting resources (#510)

- test/tracardi/test_tracardi_http_client.py
Add Tracardi HttpClient to the plugin nodes. (#629)
This PR contains tests for the client
----
> Add Tracardi HttpClient to the plugin nodes. (#629)

- app/api/domain/report_test_payload.py
- app/api/report_endpoint.py
- app/main.py
- app/service/grouping.py
- test/api/test_report.py
- test/tracardi/test_report.py
> Report server (#630)

- manual/en/docs/flow/actions/novu_plugin_action.md
- manual/en/docs/flow/password_generator_action.md
- test/plugins/unit/test_plugin_random_password_generator.py
be discarded. 
* Test your code throughly before PR.
Novu plugin action
add documentation for plugin
----
> 617 novu plugin action

- test/unit/test_tql.py
Add CONTAINS and STARTS_WTH and ENDS_WITH to IF plugin[#643](https://github.com/Tracardi/tracardi/issues/643)
fixes tracardi#643
----
> Add CONTAINS and STARTS_WTH and ENDS_WITH to IF plugin #643

- test/api/endpoints/test_event_management_endpoint.py
- test/unit/test_event_props_reshaper.py
> event reshaping feature

- .github/pull_request_template.md
- manual/en/docs/flow/actions/add_mautic_contact_action.md
- manual/en/docs/flow/actions/mailchimp_transactional_action.md
be discarded. 
Tips
* Test your code throughly before PR.
----
To make clear that you license your contribution under the MIT you have to acknowledge this by …
> misc spelling and cleanup fixes.

- manual/en/docs/flow/actions/google_translate_action.md
be discarded. 
Tips
* Test your code throughly before PR.
(#675 documentation for google translate plugin)
add documentation for google translator plugin
----
To make clear that you license your contribution under the …
> documentation for google translate plugin

- app/api/event_management_endpoint.py
Event reshaping is not working properly[#678](https://github.com/Tracardi/tracardi/issues/678)
> Event reshaping is not working properly #678

- app/api/flow_action_endpoint.py
Add infor about more plugins.[#222](https://github.com/Tracardi/tracardi-gui/issues/222)
quick bug fix for this task
----
> Add infor about more plugins.#222

- manual/en/docs/resources/mailchimp_resource.md
Missing Mailchimp resource documentation[#688](https://github.com/Tracardi/tracardi/issues/688)
----
> Missing Mailchimp resource documentation #688

- manual/en/docs/resources/mautic_resource.md
Missing mautic resource documentation[#689](https://github.com/Tracardi/tracardi/issues/689)
----
> Missing mautic resource documentation#689

- manual/en/docs/resources/civi_resource.md
Missing Civi CRM resource documentation[#687](https://github.com/Tracardi/tracardi/issues/687)
----
> Missing Civi CRM resource documentation#687

- manual/en/docs/flow/actions/contains_pattern_action.md
be discarded. 
Tips
#658 contains_pattern_plugin
docs for contains pattern plugin
----
To make clear that you license your contribution under the MIT you have to acknowledge this by …
> docs for contains pattern plugin

- app/config.py
- app/main.py
…oints
be discarded. 
Tips
676 env variable to turn off api docs
add env variable API_DOCS and configure fastapi metadate to turn off /docs and /redoc endpoints
----
To make clear …
> 676 env variable to turn off api docs

- manual/en/docs/resources/amplitude_resource.md
Please DO NOT DELETE this template. Fill it. PR without your declaration that you license your code under MIT will 
be discarded. 
Tips
Added the documentation for amplitude
I added a small description along with steps required to obtain API credentials for Amplitude
-----
To make clear that you license your …
> Added the documentation for amplitude

- README.md
- manual/en/docs/installation/docker/index.md
- manual/en/docs/installation/source/index.md
be discarded. 
Tips
----
To make clear that you license your contribution under the MIT you have to acknowledge this by …
> update docs to include redis requirement

- docs/resources/influxdb_resource.md
Added documentation for obtaining InfluxDB API credentials
be discarded. 
Tips
Added documentation for influxdb_resource.md
Added steps on how to obtain API credentials for InfluxDB
----
To make …
> Added documentation for influxdb_resource.md

- app/api/user_endpoint.py
- test/api/endpoints/test_user_preference.py
be discarded. 
Tips
tests for user preference endpoint (#718)
I added tests for user_preference_endpoint and changed method in user_endpoint /user/{id} from load_by_id (its dosen't exists in user.driver) to get_by_id
----
We need your declaration that your contribution is MIT licensed …
> 718 api tests for user preference

- docs/flow/actions/string_join_action.md
be discarded. 
Tips
Document Join string list plugin #741
added a documentation for join string list plugin which comes from https://github.com/Tracardi/tracardi/issues/741.
checked the layout displayed on a browser
----
We need your declaration that your contribution is MIT licensed …
> Document Join string list plugin #741

- app/api/user_endpoint.py
- test/api/endpoints/test_user_preference.py
be discarded. 
Tips
tests with negative path for user preference endpoint (#739)
ive added few tests with negative path and refactored delete preference endpoint that now will raise 404 if user will try to delete preference that doesn't exists
----
We need your declaration that your …
> 739 negative tests for user preference endpoint

- docs/resources/mixpanel_resource.md
Added Mixpanel documentation
be discarded. 
Tips
Update mixpanel_resource.md
Added the steps to acquire Api credentials in Mixpanel
----
To make clear that you license …
> Updated mixpanel_resource.md

- docs/resources/mqtt_resource.md
Fixes Missing documentation for MQTT resource #717
This PR Adds proper documentation for MQTT Configuration forms.
----
> Fixes Missing documentation for MQTT resource #717

- docs/resources/sendgrid_resource.md
Fixes Missing sendgrid resource documentation #724
This PR Adds proper documentation for Sendgrid Configuration.
----
> Fixes Missing sendgrid resource documentation #724

- docs/resources/salesforce_resource.md
be discarded. 
Tips
Fixed Issue #721 (https://github.com/Tracardi/tracardi/issues/721)
Issue: https://github.com/Tracardi/tracardi/issues/721
Added missing salesforce documentation.
----
We need your declaration that your contribution is MIT licensed without it, we can not merge your …
> Added salesforce_resource.md

- app/api/javascript/intercom/snippet.js
- app/api/javascript/javascript_endpoint.py
- docs/flow/actions/intercom_widget_action.md
be discarded. 
Tips
#746 intercom plugin
add endpoint for intercom snippet and docs
----
To make clear that you license your contribution under the MIT you have to acknowledge this …
> intercom plugin

- docs/flow/actions/string_similarity_action.md
be discarded. 
Tips
#731 string_similarity plugin
add string_similarity plugin docs
----
To make clear that you license your contribution under the MIT you have to acknowledge this …
> string_similarity plugin

- docs/plugins/tutorial/part1.md
- docs/plugins/tutorial/part2.md
- docs/plugins/tutorial/part3.md
be discarded. 
Tips
Fix incorrect syntax in plugins tutorial
`className` property of Spec must be a string, not a class reference. Adapt all parts of the tutorial to read the name directly from the class instead of hard-coding it as string.
See [this …
> Fix incorrect syntax in plugins tutorial

- docs/flow/actions/google_event_tracker_action.md
- docs/resources/google_analytics_tracker_resource.md
be discarded. 
Tips
#56 google analytics event tracker plugin
----
To make clear that you license your contribution under the MIT you have to acknowledge …
> google analytics tracker plugin

- docs/flow/actions/google_v4_event_tracker_action.md
- docs/resources/google_analytics_tracker_resource.md
be discarded. 
Tips
Pull request title (#774 google analytics tracker plugin)
plugin for google analytics 4 event tracker
----
To make clear that you license your contribution under …
> google analytics 4 tracker plugin

- docs/resources/discord_resource.md
be discarded. 
Tips
resource for discord plugin (#788)
----
To make clear that you license your contribution under the MIT you have to acknowledge this by using the following …
> add resource to discord plugin

- docs/events/event_tracking.md
Just fixed a small typo
be discarded. 
Tips
----
To make clear that you license your contribution under the MIT you have to …
> Fixed a small typo in event_tracking.md
